# Generated by Django 4.1.7 on 2023-04-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcategory_product_discount_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
    ]
