# Generated by Django 4.1.7 on 2023-04-21 11:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='title',
            field=ckeditor.fields.RichTextField(default=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='text',
            field=ckeditor.fields.RichTextField(default=True),
        ),
    ]
