# Generated by Django 4.1.7 on 2023-04-21 12:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_area', '0002_privacypolicy_title_alter_privacypolicy_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacypolicy',
            old_name='title',
            new_name='one',
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='three',
            field=ckeditor.fields.RichTextField(default=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='two',
            field=ckeditor.fields.RichTextField(default=True),
        ),
    ]
