# Generated by Django 4.1.7 on 2023-04-21 12:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_area', '0003_rename_title_privacypolicy_one_privacypolicy_three_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=True),
        ),
    ]
