# Generated by Django 4.1.7 on 2023-04-21 12:26

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_area', '0004_alter_privacypolicy_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='text2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='text',
            field=ckeditor.fields.RichTextField(default=True),
        ),
    ]
